In [ ]:
import numpy as np
import matplotlib as plt
import pandas as pd

# Machine Learning - Linear and Logistic Regression using Gradient Descent

## 1. Implementing Linear Regression using Gradient Descent

In [ ]:
# load data # DataFrame으로 저장
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
df = pd.read_csv(url, header=None)

In [ ]:
df

       0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
# select only iris-setosa
df_setosa = df[df[4] == "Iris-setosa"]

In [ ]:
df_setosa

      0    1    2    3            4
0   5.1  3.5  1.4  0.2  Iris-setosa
1   4.9  3.0  1.4  0.2  Iris-setosa
2   4.7  3.2  1.3  0.2  Iris-setosa
3   4.6  3.1  1.5  0.2  Iris-setosa
4   5.0  3.6  1.4  0.2  Iris-setosa
5   5.4  3.9  1.7  0.4  Iris-setosa
6   4.6  3.4  1.4  0.3  Iris-setosa
7   5.0  3.4  1.5  0.2  Iris-setosa
8   4.4  2.9  1.4  0.2  Iris-setosa
9   4.9  3.1  1.5  0.1  Iris-setosa
10  5.4  3.7  1.5  0.2  Iris-setosa
11  4.8  3.4  1.6  0.2  Iris-setosa
12  4.8  3.0  1.4  0.1  Iris-setosa
13  4.3  3.0  1.1  0.1  Iris-setosa
14  5.8  4.0  1.2  0.2  Iris-setosa
15  5.7  4.4  1.5  0.4  Iris-setosa
16  5.4  3.9  1.3  0.4  Iris-setosa
17  5.1  3.5  1.4  0.3  Iris-setosa
18  5.7  3.8  1.7  0.3  Iris-setosa
19  5.1  3.8  1.5  0.3  Iris-setosa
20  5.4  3.4  1.7  0.2  Iris-setosa
21  5.1  3.7  1.5  0.4  Iris-setosa
22  4.6  3.6  1.0  0.2  Iris-setosa
23  5.1  3.3  1.7  0.5  Iris-setosa
24  4.8  3.4  1.9  0.2  Iris-setosa
25  5.0  3.0  1.6  0.2  Iris-setosa
26  5.0  3.4  1.6  0.4  Iris-setosa
27  5.2  3.5  1.5  0.2  Iris-setosa
28  5.2  3.4  1.4  0.2  Iris-setosa
29  4.7  3.2  1.6  0.2  Iris-setosa
30  4.8  3.1  1.6  0.2  Iris-setosa
31  5.4  3.4  1.5  0.4  Iris-setosa
32  5.2  4.1  1.5  0.1  Iris-setosa
33  5.5  4.2  1.4  0.2  Iris-setosa
34  4.9  3.1  1.5  0.1  Iris-setosa
35  5.0  3.2  1.2  0.2  Iris-setosa
36  5.5  3.5  1.3  0.2  Iris-setosa
37  4.9  3.1  1.5  0.1  Iris-setosa
38  4.4  3.0  1.3  0.2  Iris-setosa
39  5.1  3.4  1.5  0.2  Iris-setosa
40  5.0  3.5  1.3  0.3  Iris-setosa
41  4.5  2.3  1.3  0.3  Iris-setosa
42  4.4  3.2  1.3  0.2  Iris-setosa
43  5.0  3.5  1.6  0.6  Iris-setosa
44  5.1  3.8  1.9  0.4  Iris-setosa
45  4.8  3.0  1.4  0.3  Iris-setosa
46  5.1  3.8  1.6  0.2  Iris-setosa
47  4.6  3.2  1.4  0.2  Iris-setosa
48  5.3  3.7  1.5  0.2  Iris-setosa
49  5.0  3.3  1.4  0.2  Iris-setosa

In [ ]:
# select only 0~3 columns
df_setosa = df_setosa.iloc[:, :4]
df_setosa

      0    1    2    3
0   5.1  3.5  1.4  0.2
1   4.9  3.0  1.4  0.2
2   4.7  3.2  1.3  0.2
3   4.6  3.1  1.5  0.2
4   5.0  3.6  1.4  0.2
5   5.4  3.9  1.7  0.4
6   4.6  3.4  1.4  0.3
7   5.0  3.4  1.5  0.2
8   4.4  2.9  1.4  0.2
9   4.9  3.1  1.5  0.1
10  5.4  3.7  1.5  0.2
11  4.8  3.4  1.6  0.2
12  4.8  3.0  1.4  0.1
13  4.3  3.0  1.1  0.1
14  5.8  4.0  1.2  0.2
15  5.7  4.4  1.5  0.4
16  5.4  3.9  1.3  0.4
17  5.1  3.5  1.4  0.3
18  5.7  3.8  1.7  0.3
19  5.1  3.8  1.5  0.3
20  5.4  3.4  1.7  0.2
21  5.1  3.7  1.5  0.4
22  4.6  3.6  1.0  0.2
23  5.1  3.3  1.7  0.5
24  4.8  3.4  1.9  0.2
25  5.0  3.0  1.6  0.2
26  5.0  3.4  1.6  0.4
27  5.2  3.5  1.5  0.2
28  5.2  3.4  1.4  0.2
29  4.7  3.2  1.6  0.2
30  4.8  3.1  1.6  0.2
31  5.4  3.4  1.5  0.4
32  5.2  4.1  1.5  0.1
33  5.5  4.2  1.4  0.2
34  4.9  3.1  1.5  0.1
35  5.0  3.2  1.2  0.2
36  5.5  3.5  1.3  0.2
37  4.9  3.1  1.5  0.1
38  4.4  3.0  1.3  0.2
39  5.1  3.4  1.5  0.2
40  5.0  3.5  1.3  0.3
41  4.5  2.3  1.3  0.3
42  4.4  3.2  1.3  0.2
43  5.0  3.5  1.6  0.6
44  5.1  3.8  1.9  0.4
45  4.8  3.0  1.4  0.3
46  5.1  3.8  1.6  0.2
47  4.6  3.2  1.4  0.2
48  5.3  3.7  1.5  0.2
49  5.0  3.3  1.4  0.2

In [ ]:
# to numpy array
df_setosa = df_setosa.to_numpy()

In [ ]:
df_setosa

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2]])

In [ ]:
# data X, predictor variable y
# 여기서 X랑 y가 무엇인가?!
X = df_setosa[:, :3]
y = df_setosa[:, 3]
# 데이터 X는 0~2열로 구성되며, y는 3열로 구성됩니다.

In [ ]:
X

array([[5.1, 3.5, 1.4],
       [4.9, 3. , 1.4],
       [4.7, 3.2, 1.3],
       [4.6, 3.1, 1.5],
       [5. , 3.6, 1.4],
       [5.4, 3.9, 1.7],
       [4.6, 3.4, 1.4],
       [5. , 3.4, 1.5],
       [4.4, 2.9, 1.4],
       [4.9, 3.1, 1.5],
       [5.4, 3.7, 1.5],
       [4.8, 3.4, 1.6],
       [4.8, 3. , 1.4],
       [4.3, 3. , 1.1],
       [5.8, 4. , 1.2],
       [5.7, 4.4, 1.5],
       [5.4, 3.9, 1.3],
       [5.1, 3.5, 1.4],
       [5.7, 3.8, 1.7],
       [5.1, 3.8, 1.5],
       [5.4, 3.4, 1.7],
       [5.1, 3.7, 1.5],
       [4.6, 3.6, 1. ],
       [5.1, 3.3, 1.7],
       [4.8, 3.4, 1.9],
       [5. , 3. , 1.6],
       [5. , 3.4, 1.6],
       [5.2, 3.5, 1.5],
       [5.2, 3.4, 1.4],
       [4.7, 3.2, 1.6],
       [4.8, 3.1, 1.6],
       [5.4, 3.4, 1.5],
       [5.2, 4.1, 1.5],
       [5.5, 4.2, 1.4],
       [4.9, 3.1, 1.5],
       [5. , 3.2, 1.2],
       [5.5, 3.5, 1.3],
       [4.9, 3.1, 1.5],
       [4.4, 3. , 1.3],
       [5.1, 3.4, 1.5],
       [5. , 3.5, 1.3],
       [4.5, 2.3, 1.3],
       [4.4, 3.2, 1.3],
       [5. , 3.5, 1.6],
       [5.1, 3.8, 1.9],
       [4.8, 3. , 1.4],
       [5.1, 3.8, 1.6],
       [4.6, 3.2, 1.4],
       [5.3, 3.7, 1.5],
       [5. , 3.3, 1.4]])

In [ ]:
# data X needs ones in the first column
X = np.insert(X, 0, 1, axis=1) # X 데이터의 첫 번째 열에 1로 이루어진 열을 추가하여
X                              #  행렬 연산을 위한 상수항을 포함시킵니다.

array([[1. , 5.1, 3.5, 1.4],
       [1. , 4.9, 3. , 1.4],
       [1. , 4.7, 3.2, 1.3],
       [1. , 4.6, 3.1, 1.5],
       [1. , 5. , 3.6, 1.4],
       [1. , 5.4, 3.9, 1.7],
       [1. , 4.6, 3.4, 1.4],
       [1. , 5. , 3.4, 1.5],
       [1. , 4.4, 2.9, 1.4],
       [1. , 4.9, 3.1, 1.5],
       [1. , 5.4, 3.7, 1.5],
       [1. , 4.8, 3.4, 1.6],
       [1. , 4.8, 3. , 1.4],
       [1. , 4.3, 3. , 1.1],
       [1. , 5.8, 4. , 1.2],
       [1. , 5.7, 4.4, 1.5],
       [1. , 5.4, 3.9, 1.3],
       [1. , 5.1, 3.5, 1.4],
       [1. , 5.7, 3.8, 1.7],
       [1. , 5.1, 3.8, 1.5],
       [1. , 5.4, 3.4, 1.7],
       [1. , 5.1, 3.7, 1.5],
       [1. , 4.6, 3.6, 1. ],
       [1. , 5.1, 3.3, 1.7],
       [1. , 4.8, 3.4, 1.9],
       [1. , 5. , 3. , 1.6],
       [1. , 5. , 3.4, 1.6],
       [1. , 5.2, 3.5, 1.5],
       [1. , 5.2, 3.4, 1.4],
       [1. , 4.7, 3.2, 1.6],
       [1. , 4.8, 3.1, 1.6],
       [1. , 5.4, 3.4, 1.5],
       [1. , 5.2, 4.1, 1.5],
       [1. , 5.5, 4.2, 1.4],
       [1. , 4.9, 3.1, 1.5],
       [1. , 5. , 3.2, 1.2],
       [1. , 5.5, 3.5, 1.3],
       [1. , 4.9, 3.1, 1.5],
       [1. , 4.4, 3. , 1.3],
       [1. , 5.1, 3.4, 1.5],
       [1. , 5. , 3.5, 1.3],
       [1. , 4.5, 2.3, 1.3],
       [1. , 4.4, 3.2, 1.3],
       [1. , 5. , 3.5, 1.6],
       [1. , 5.1, 3.8, 1.9],
       [1. , 4.8, 3. , 1.4],
       [1. , 5.1, 3.8, 1.6],
       [1. , 4.6, 3.2, 1.4],
       [1. , 5.3, 3.7, 1.5],
       [1. , 5. , 3.3, 1.4]])

In [ ]:
# make linear function: h(x)
# 선형 함수 h(x)를 정의합니다. theta는 가중치(weight) 벡터이고, x는 입력 변수입니다.
def linear_function(theta, x):
  '''
  theta: w0, w1, ..., wn
  x: x0=1, x1, ..., xn
  '''
  return np.dot(theta, x)

In [ ]:
X[1] # 1번 행

array([1. , 4.9, 3. , 1.4])

In [ ]:
# test linear function
# 비용 함수 J(theta)를 정의합니다.
theta_test = np.random.rand(4)
linear_function(theta_test, X[1])

4.614970153455803

In [ ]:
# define cost function
# 이 함수는 예측값과 실제값 사이의 오차의 제곱을 계산하고, 평균을 구합니다.
def cost_linear(theta, X, y):
  '''
  theta: w0, w1, ..., wn
  X: data
  y: predictor variable
  '''
  # m: number of data
  m = len(X)

  cost = 0
  for i in range(m):
    cost += np.power(linear_function(theta, X[i]) - y[i], 2)
  cost = cost * 1/m
  return cost

# 이 비용은 모델의 예측 성능을 평가하고, 경사 하강법에서 최적화할 목적 함수로 사용됩니다.

# theta는 선형 회귀 모델의 가중치(계수)를 나타내며,
# theta = [w0, w1, ..., wn] 형태의 벡터입니다.
# 이 가중치는 입력 변수(X)와 함께 선형 함수를 통해 예측값을 계산하는 데 사용
# 경사 하강법은 이 가중치를 최적화하여 오차를 최소화하는 값을 찾는 알고리즘입니다.

위 코드는 선형 회귀 모델의 비용 함수 J(theta)를 계산하는 함수입니다. 비용 함수는 모델의 예측값과 실제값 사이의 오차를 측정하여 모델의 성능을 평가하는 데 사용됩니다.

함수의 입력은 다음과 같습니다:

- `theta`: 가중치(w0, w1, ..., wn)를 포함한 벡터
- `X`: 입력 데이터
- `y`: 실제값 (예측 변수)

함수 내부에서는 다음과 같은 작업이 수행됩니다:

1. `m = len(X)`: 데이터의 개수를 m에 저장합니다.
2. `cost = 0`: 비용 값을 초기화합니다.
3. `for i in range(m):`: 데이터 개수만큼 반복합니다.
    - `cost += np.power(linear_function(theta, X[i]) - y[i], 2)`: 예측값과 실제값의 차이의 제곱을 누적하여 비용을 계산합니다.
4. `cost = cost * 1/m`: 누적된 비용을 데이터 개수로 나누어 평균 비용을 구합니다.

마지막으로 `cost` 값을 반환하여 비용 함수의 결과를 돌려줍니다. 이 비용은 모델의 예측 성능을 평가하고, 경사 하강법에서 최적화할 목적 함수로 사용됩니다.

theta는 선형 회귀 모델의 가중치(계수)를 나타내며, theta = [w0, w1, ..., wn] 형태의 벡터입니다. 이 가중치는 입력 변수(X)와 함께 선형 함수를 통해 예측값을 계산하는 데 사용됩니다. 경사 하강법은 이 가중치를 최적화하여 오차를 최소화하는 값을 찾는 알고리즘입니다.

In [ ]:
# test cost function
cost_linear(theta_test, X, y)

10.137402933882445

In [ ]:
# 비용 함수 J(theta)의 각 가중치에 대한 편미분인 기울기를 계산하는 함수입니다.
# j는 특정 가중치의 인덱스를 의미하며,
# dJ_dw는 해당 가중치에 대한 기울기 값을 반환합니다.
def compute_jth_linear_gradient(theta, j, X, y):
  '''
  theta: w0, w1, ..., wn
  j: jth feature
  X: data
  y: predictor variable
  '''
  # m: number of data
  m = len(X)

  dJ_dw = 0
  for i in range(m):
    dJ_dw += (linear_function(theta, X[i]) - y[i]) * X[i][j]
  dJ_dw = dJ_dw * (2/m)

  return dJ_dw

위 코드는 선형 회귀 모델의 비용 함수 J(theta)를 편미분하여 각 가중치(w0, w1, ..., wn)에 대한 기울기를 계산하는 함수입니다.

함수의 입력은 다음과 같습니다:

- `theta`: 가중치(w0, w1, ..., wn)를 포함한 벡터
- `j`: 특정 가중치의 인덱스
- `X`: 입력 데이터
- `y`: 실제값 (예측 변수)

함수 내부에서는 다음과 같은 작업이 수행됩니다:

1. `m = len(X)`: 데이터의 개수를 m에 저장합니다.
2. `dJ_dw = 0`: 기울기 값을 초기화합니다.
3. `for i in range(m):`: 데이터 개수만큼 반복합니다.
    - `dJ_dw += (linear_function(theta, X[i]) - y[i]) * X[i][j]`: 오차 (예측값과 실제값의 차이)에 입력 데이터의 j번째 특성 값을 곱하여 기울기를 누적합니다.
4. `dJ_dw = dJ_dw * (2/m)`: 누적된 기울기 값을 데이터 개수로 나누어 기울기의 평균을 구합니다.

마지막으로 `dJ_dw` 값을 반환하여 특정 가중치에 대한 기울기 값을 계산합니다. 이러한 기울기 값은 경사 하강법에서 가중치를 업데이트하는 데 사용됩니다.

In [ ]:
# test gradient
compute_jth_linear_gradient(theta_test, 1, X, y)

31.93064361885085

In [ ]:
X.shape

(50, 4)

In [ ]:
# 경사하강법
def linear_gradient_descent(X, y):
  '''
  X: data
  y: predictor variable
  '''
  # m: number of data, n: number of feature
  m = len(X)
  n = X.shape[1] # 특성(열) 개수 저장

  # hyperparameter
  alpha = 0.01 # learning rate
  epsilon = 10 ** -4 # 수렴조건 (비용의 차이가 이 값보다 작으면 알고리즘 중지)

  # initialization
  theta = np.random.rand(n) # 가중치 무작위로 초기화

  # cost J
  J = np.zeros(1000) # 비용함수 J(theta) 저장 배열 초기화

  # gradient descent
  iter = 1 # 반복 횟수 초기화
  while True:

    # update gradient
    for j in range(n):
      theta[j] = theta[j] - alpha * compute_jth_linear_gradient(theta, j, X, y)
      #  해당 가중치를 "학습률"과 "해당 가중치에 대한 기울기"를 곱한 값으로 업데이트

    # compute cost
    J[iter] = cost_linear(theta, X, y) # 현재 가중치로 계산한 비용을 J 배열에 저장
    print(f"cost at time {iter}: {J[iter]}") # 현재 반복에서의 비용을 출력
    print(f"cost difference at {iter}: {np.abs(J[iter] - J[iter - 1])}") # 비용의 변화 출력

    # convergence condition
    # 비용의 변화가 수렴 조건을 만족하면 반복 중지
    if np.abs(J[iter] - J[iter - 1]) < epsilon:
      break

    iter += 1 # 반복 횟수를 증가

  return
# 최종적으로 함수는 반환값이 없고,
# 최적화된 가중치 theta를 사용하여 모델을 학습시킵니다.
# 이러한 과정을 통해 경사 하강법을 사용하여 선형 회귀 모델의 가중치를 최적화하고,
# 비용을 최소화하는 방향으로 모델을 업데이트합니다.

위 코드는 경사 하강법을 사용하여 선형 회귀 모델의 가중치를 최적화하는 함수입니다.

함수의 입력은 다음과 같습니다:
- `X`: 입력 데이터
- `y`: 실제값 (예측 변수)

함수 내부에서는 다음과 같은 작업이 수행됩니다:

1. `m = len(X)`: 데이터의 개수를 m에 저장합니다.
2. `n = X.shape[1]`: 입력 데이터의 특성(열) 개수를 n에 저장합니다.
3. `alpha = 0.01`: 학습률(learning rate)로, 가중치를 업데이트할 때 사용되는 스텝의 크기를 결정합니다.
4. `epsilon = 10 ** -4`: 수렴 조건으로, 비용의 차이가 이 값보다 작으면 알고리즘을 중지합니다.
5. `theta = np.random.rand(n)`: 가중치를 무작위로 초기화합니다.
6. `J = np.zeros(1000)`: 비용 함수 J(theta)의 값들을 저장할 배열을 초기화합니다.
7. `iter = 1`: 반복 횟수를 초기화합니다.

그리고 아래의 작업들을 반복하면서 경사 하강법을 수행합니다:

8. `for j in range(n):`: 각 가중치에 대해 반복합니다.
   - `theta[j] = theta[j] - alpha * compute_jth_linear_gradient(theta, j, X, y)`: 해당 가중치를 학습률과 해당 가중치에 대한 기울기를 곱한 값으로 업데이트합니다.
9. `J[iter] = cost_linear(theta, X, y)`: 현재 가중치로 계산한 비용을 J 배열에 저장합니다.
10. `print(f"cost at time {iter}: {J[iter]}")`: 현재 반복에서의 비용을 출력합니다.
11. `print(f"cost difference at {iter}: {np.abs(J[iter] - J[iter - 1])}")`: 현재 반복에서의 비용의 변화를 출력합니다.
12. `if np.abs(J[iter] - J[iter - 1]) < epsilon: break`: 비용의 변화가 수렴 조건을 만족하면 반복을 중지합니다.
13. `iter += 1`: 반복 횟수를 증가시킵니다.

최종적으로 함수는 반환값이 없고, 최적화된 가중치 theta를 사용하여 모델을 학습시킵니다.

이러한 과정을 통해 경사 하강법을 사용하여 선형 회귀 모델의 가중치를 최적화하고, 비용을 최소화하는 방향으로 모델을 업데이트합니다.

In [ ]:
# test linear regression
result = linear_gradient_descent(X, y)

cost at time 1: 3.552881903514511
cost difference at 1: 3.552881903514511
cost at time 2: 0.47684351428085114
cost difference at 2: 3.07603838923366
cost at time 3: 0.08797866897082864
cost difference at 3: 0.3888648453100225
cost at time 4: 0.03897599655053079
cost difference at 4: 0.04900267242029784
cost at time 5: 0.03284465011234828
cost difference at 5: 0.006131346438182514
cost at time 6: 0.032081007856700344
cost difference at 6: 0.0007636422556479353
cost at time 7: 0.031975079031868664
cost difference at 7: 0.00010592882483168031
cost at time 8: 0.03194459240658096
cost difference at 8: 3.0486625287706737e-05

## 2. Implementing Logistic Regression using Gradient Descent

In [ ]:
# back to our iris dataset
df

In [ ]:
# show unique labels

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [ ]:
# get only iris-setosa and iris-versicolor

In [ ]:
# change the label to 0 and 1

In [ ]:
# make new_df to numpy arrays

In [ ]:
# data: X and predictor variable y

In [ ]:
# check X and y

In [ ]:
# augment X with 1's in the leftmost column

In [ ]:
# simple sigmoid function
def sigmoid_func(z):
  '''
  z: real value
  '''
  return

In [ ]:
# test sigmoid function
print(sigmoid_func(0))
print(sigmoid_func(10.2))

0.5
0.9999628310628971

In [ ]:
# our hypothesis function
def compute_logistic_func(theta, x):
  '''
  theta: w0, w1, ..., wn
  x: 1, x1, x2, ..., xn
  '''

  return

In [ ]:
# test logistic function
test_theta = np.random.rand(5)
compute_logistic_func(test_theta, X[1])

In [ ]:
# compute gradient
def compute_jth_log_gradient(theta, j, X, y):
  '''
  theta = w0, w1, ..., wn
  j: jth feature
  X: data
  y: predictor variable
  '''
  return

In [ ]:
# test gradient function
compute_jth_log_gradient(test_theta, 1, X, y)

In [ ]:
# gradient descent for logistic regression
def logistic_gradient_descent(X, y):
  '''
  X: data
  y: predictor variable
  '''

  return

In [ ]:
# run logistic regression
logistic_gradient_descent(X, y)